# vim:ft=yaml ts=2 shiftwidth=2:
#
os:
  - linux
sudo: required
language: c
services:
  - docker
before_install:
  - docker build -t ring3/ocaml .
  - docker ps -a
script:
  - chmod -R o+w .
  - docker run -t -t -v $PWD:/mnt ring3/ocaml make -C /mnt

deploy:
  provider: releases
  api_key:
    secure: t4c4vIYXipKLaDk5eixFdgLzuKuUilsqRbjVnCH03r8yUenXDdWfiJQWzUDxnk/figYeWI1hGfqwczahF9vUZMXascTNDjTNUK42PvGWLjnGb1gXEmp2UK8VsS6PHprrPrkA2uyEOZHZR3U5m5ouTU1NIlzkruqnBgZnFo0SNmgl8NIuC2hnAa9SAPcXbu+z0UR6djTcJfQTntkgV7NSm308jqgHqpOyGz+QB1pTYlwrp7A0FVy4Axb0gWOuWccn5m5xpOPKdrkUN74fNBrvJ3KjkW0veJMfYjETpeNAvPetPHGzXSByXqKysTqlYadMxfXVPIj0isoKNdfg7MjMHx72QCvh2WEIm8iedXwztNlNK2pX+LouEvhaeJkoJE4u7PLqcJhZV1YUKhpwoHpKNJbD9m6eoGwVh/+izpt3rbaPRv05cRLzclYoguS5fb3PdtHPWgoLaSIjBDghghD9G1lxlSN4nw1uEJaGjdnNhWTulOxjzQnauVIv38kdYIdjZ1NYHxNMXWEfk0sMMUGPTF8j5F8v204LKUIvRTndhEYmVegT4mI6AMa0gnE2gcaTw2x9yOGwjRZM634EaNsRzgI0mhiYyTbpMTRwW8zIqV8LM72r0JME3UnJmO9PLBdqzdLDsBGfnlEyLzC7mz/hnj6GHXVUPGdk/rEKwTC9cIg=
  file: src/test-vm.xen.gz
  skip_cleanup: true
  on:
    tags: true
