language: c
sudo: required
install: 
    - curl -O https://raw.githubusercontent.com/lindig/xen-test-vm/master/travis.sh 
    - curl -O https://raw.githubusercontent.com/lindig/xen-test-vm/master/setup.sh 
script:
    - bash -ex travis.sh
    - bash -ex setup.sh
    - make
os:
  - linux
