os:
- linux
sudo: required
language: c
services:
- docker
before_install:
- docker build -t ring3/ocaml .
- docker images
- rvm use ruby-2.2.3
script:
- chmod -R o+w src/
- docker run -t -t -v $PWD:/mnt ring3/ocaml make -C /mnt
- sudo chown travis.travis src/test-vm.xen.gz
- ls -lh src/
deploy:
  provider: releases
  api_key:
    # Create this key using "travis setup releases" on the command line.
    # Deployment on Travis is triggered when 
    # (1) a release is tagged
    # (2) it is built from the repo named under on.repo below
    # Hence, it is safe to built this with Travis from a forked
    # (private) repo as the release step is not triggered.
    secure: ZnBqsgSETjOW//LKgXs80BTVaNnTvCxsNP0NiY7iYK/VwvsAKbyguSLQH8irtRmPAYVzxiWAgRqZzftMGW8mIocwwHGdCoQBacnOwQAnjPfCA9ir+lXWVYS4Wy5Vx7GLTExRLUnmBTxN8ynbXC8RxNExkPILjYT+Q0P0GR93LuDVHgVNbpBNhmQaGZucpmrPutdBcl18ZOPyJ5Coj1iAOwfeSDgCl+WSIfwRP+T+lGUHu99/J6ZCplYZUAGdbr1+2ndmu/bPbWegbasEVLzZgg6Crl3gRaDbKEkT4ZtyyBDKvw8zuZ3tOQTBgSbc0NPnjv7hG7AMaM7A3Hs6D8MuwlpVY3R3Q6KpM2MCjx9CF8vj8LoU1SRGeGW1000XiLdzbaz68NzWHZ3h4pZw3LkUlJAuWQk5ke76IAswT7syar77eagaK2/XjAjxOjrhF8h1iqpuzDuYYioZ0s3/sU5dLqVZDHlSrIB/DTqPBuhs89suq6qyyG1CkSBU32he/xj4IU00MTjS4IdZ5/N/IY7btnn0pOmkCRxH1mKiB903TslBfKcHEl7hOIynS+O2oXUzSsvdF4NArWeWvTxNKIOfVuBJ6hiuGsf79FHihOR26YuucRE/gZR8avOoDfeB1NFIuJAWE0ILga2QYtTxlaZ5TQw8+nmQIZesBnwP7/bHDEY=
  file: src/test-vm.xen.gz
  skip_cleanup: true
  on:
    tags: true
