language: c
sudo: required
install: curl -O https://raw.githubusercontent.com/lindig/xen-test-vm/master/travis.sh 
install: curl -O https://raw.githubusercontent.com/lindig/xen-test-vm/master/setup.sh 
script: bash -ex travis.sh
script: bash -ex setup.sh
script: make
os:
  - linux
